### ISSUE TITLE
Use cloudpickle

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/lahja#172]
I'm thinking we should use `cloudpickle` over stdlib pickle as it is able to pickle more things than the stdlib pickle can...

**Comment by cburgdorf** [comment]
That sounds interesting indeed! But we should absolutely look into the performance impact for such a change.

**Comment by pipermerriam** [comment]
The other alternative is to go ahead and drop pickle and have event classes be in charge of their own serialization.  Very likely that path also gains us some additional performance.

**Comment by cburgdorf** [comment]
>The other alternative is to go ahead and drop pickle and have event classes be in charge of their own serialization

Yeah probably the better direction. Event classes can have a serializer injected and we might ship with default serializers based on `pickle` and maybe `cloudpickle` but one can always go down to the metal and serialize in a custom way. This would allow full flexibility without giving up convenience.

**Comment by pipermerriam** [comment]
I'm replacing this with https://github.com/ethereum/lahja/issues/173
