### ISSUE TITLE
Transfer down `esophagus` consistently rejected 

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/lahja#19]
## What happened

Tried to send nutritional matter down esophagus

## What did you expect to happen

Esophagus transfers food to internal factory to be converted to energy

## What actually happend

factory returned food in a partially processed state

## Steps to reproduce

Give lahja food

## How can it be fixed

I suspect spending a day at home watching cartoons but test is ongoing.

**Comment by cburgdorf** [comment]
Tried various approaches including some medicine, snuggle as well as tons of cartoon time. Integration tests will take a full night to run but I'm fairly confident for the system to run stable again. Will re-open if issue comes up again.
