### ISSUE TITLE
Only relay messages to processes that hold subscriptions to the event

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/lahja#2]
## What was wrong?

Currently, if one broadcasts a message and not exclusively limit the scope of recipients (`BroadcastConfig`) it will be relayed from the coordinator process to all other endpoints.   

## How can it be fixed?

I guess it should be doable to make the coordinator process (in other words the `EventBus` aware of which endpoint is subscribed to which event and hence only relay messages to interested parties.

**Comment by pipermerriam** [comment]
This was done.
