### ISSUE TITLE
Look into py-nng as a possible transport layer

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/lahja#31]
## What was wrong?

Py-nng (nanomesage next generation) looks like a good potential fit for a blazingly fast transport layer.

https://pynng.readthedocs.io/en/latest/index.html

**Comment by pipermerriam** [comment]
Yes, a very brief look at NNG and the python bindings look very promising.

**Comment by pipermerriam** [comment]
I think we aren't doing this anytime soon.
