### ISSUE TITLE
An exception in a handler can halt message processing

### ISSUE THREAD

**Issue by lithp** [ethereum/lahja#38]
Currently the code for `_connect_receiving_queue` looks like this (and `_connect_internal_queue` has the same problem):

```python
    async def _connect_receiving_queue(self) -> None:
        self._receiving_loop_running.set()
        while self._running:
            (item, config) = await self._receiving_queue.get()
            event = self._decompress_event(item)
            self._process_item(event, config)
```

The problem is twofold.
- If `_process_item` encounters an exception (which is particularly likely in one of the handlers since those are provided by the user) this function will stop processing events.
- Because `asyncio.gather(asyncio.ensure_future(self._connect_receiving_queue(), ...))` is used, that exception will not be logged until the program exits, messages will be silently dropped.

### Here's a failing test:

```python
class RemoveItem(BaseEvent):
    def __init__(self, item):
        super().__init__()
        self.item = item

@pytest.mark.asyncio
async def test_exceptions_suppressed(endpoint) -> None:

    the_set = {1, 3}
    def handle(message: RemoveItem):
        the_set.remove(message.item)

    endpoint.subscribe(RemoveItem, handle)

    endpoint.broadcast(RemoveItem(1))
    await asyncio.sleep(0.05)
    assert the_set == {3}

    endpoint.broadcast(RemoveItem(2))
    await asyncio.sleep(0.05)
    assert the_set == {3}

    endpoint.broadcast(RemoveItem(3))
    await asyncio.sleep(0.05)
    assert the_set == {}   # it fails here
```

**Comment by pipermerriam** [comment]
Do you see a way we could use `asyncio.wait((thing_that_could_fail for .. in ...), return_when=concurrent.futures.FIRST_EXCEPTION)` to make the exceptions show up faster?

**Comment by lithp** [comment]
Spent some time looking at this and opened a PR. I think `asyncio.wait()` would work, but that requires calling it from a coroutine. After playing with asyncio it looks like `asyncio.gather()` actually does the right thing, but only if it's awaited from inside a coro. Since these things are spawned from `start_serving_nowait`, which is not a coroutine, it looks like turning this into a call to `ensure_future` does what we need.
