### ISSUE TITLE
AttributeError: 'Endpoint' object has no attribute '_name'

### ISSUE THREAD

**Issue by carver** [ethereum/lahja#87]
### Code that produced the error

I guess a broadcast call from an endpoint created with `Endpoint()`. 

### Full error output 

```sh
future: <Task finished coro=<Endpoint.broadcast() done, defined at .../lahja/endpoint.py:405> exception=AttributeError("'Endpoint' object has no attribute '_name'",)>
Traceback (most recent call last):
  File "..../lahja/endpoint.py", line 412, in broadcast
    item._origin = self.name
  File ".../lahja/endpoint.py", line 196, in name
    return self._name
AttributeError: 'Endpoint' object has no attribute '_name'
```

### Environment

v0.12.0

## How can it be fixed?

Either the name should be required on init, or `_name` shouldn't be required at all (maybe an internally generated one, if necessary).

I think I prefer not needing a name

**Comment by pipermerriam** [comment]
I think that's old code.  nuke your `lahja` and then re-install from dev requirements.  I think the `git` requirement that is in there right now doesn't replace an existing install

**Comment by pipermerriam** [comment]
https://github.com/ethereum/lahja/pull/75 is the PR that makes `name` a constructor of `Endpoint`

**Comment by carver** [comment]
:+1: just wanted to capture it against v0.12.0. Didn't try master. Will close as fixed.
