### ISSUE TITLE
Several APIs (including stream) should accept a CancelToken parameter

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/lahja#9]
## What was wrong?

There's currently no builtin way to unsubscribe from the `stream` API. See discussion: https://github.com/ethereum/py-evm/pull/1310#discussion_r219179856

## How can it be fixed?

e.g.
`stream(SomeEvent, cancel_token=token)`

**Comment by pipermerriam** [comment]
Closing as I don't think we're doing this anymore.  See this comment for why: https://github.com/ethereum/lahja/pull/11#pullrequestreview-158660912
